name: Valgrind

on:
  push:
    branches: [ "main", "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        recursive: true

    - name: Install Valgrind
      run: |
        sudo apt install valgrind
        echo "Valgrind installed"

    - name: Build project
      run: |
        ./script/bootstrap.sh
        ./local/bam/bam config=debug platform=linux_x86_64 compiler=gcc

    - name: Run Tests with Valgrind
      run: |
        valgrind --track-origins=yes --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./local/linux_x86_64/gcc/debug/dl_tests

